### ISSUE TITLE
Error parsing reference: "golang:latest AS build-env" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by paragbharne** [chzbrgr71/go-web#1]
https://github.com/chzbrgr71/go-web/blob/3c122a0150d547fd85444ebcea825e4b7105b141/Dockerfile#L2

**Comment by carlosalexei** [comment]
I think the problem is the docker version on jenkins build node. I have the same problem until I update to the latest docker version.

**Comment by paragbharne** [comment]
Thanks dear.....
